SELECT A.AUTHOR_ID,
       A.AUTHOR_NAME,
       B.CATEGORY,
       SUM(B.PRICE * S.SALES) TOTAL_SALES
FROM BOOK_SALES S 
LEFT JOIN BOOK B
ON S.BOOK_ID = B.BOOK_ID AND SUBSTR(s.sales_date,1,7) = '2022-01'
INNER JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY 3,2,1
ORDER BY 1, 3 DESC;